### ISSUE TITLE
add parental control, feed amount, slow_feed and food status

### ISSUE THREAD

**Issue by Ceel84** [dgreif/homebridge-petsafe-smart-feed#30]
pls add parental control, feed amount, slow_feed and food status

**Comment by dgreif** [comment]
All of these features are readily available from the PetSafe app.  Since I can't see a need to _automate_ them, I think the current accessory with a simple switch is sufficient.  Feed amount is particularly tricky because there is no generic "slider" in HomeKit, which is why I have this available as a config option (falling back to the last feed amount by default)
