### ISSUE TITLE
SetTimeout in rest client prevents nodejs from exiting.

### ISSUE THREAD

**Issue by Reidsy** [dgreif/homebridge-petsafe-smart-feed#41]
When using the `SmartFeedApi` directly, the call to `setTimeout` in `RestClient.updateIdToken` introduced in https://github.com/dgreif/homebridge-petsafe-smart-feed/commit/be3397f8f3db18a140d2d5955590bd88dd872949 causes nodejs to wait forever preventing scripts from cleanly exiting.

To Reproduce:
```
const token = "ABC123";
const PetSafe = require('homebridge-petsafe-smart-feed/lib/api');

let sf = new PetSafe.SmartFeedApi({ token });
sf.getFeeders().then((feeders) => {
  return feeders[0].getLastFeedingMessage();
}).then((lastFeedingMessage) => {
  console.log("Will wait forever and never exit");
});
```

Possible solutions:
- provide a configuration option to disable the hourly token renewal and instead renew after receiving a 401
- provide a method to cancel the timeout
- renew the token as needed right before making a request

**Comment by dgreif** [comment]
This isn't a super high priority for me since the homebridge server already handles hanging processes. I'd welcome a PR if you have the time. The approach I'd probably take is keeping track of the last time the token was refreshed, and then refreshing it when we _need_ to use it if it's been more than the set amount of time since the last refresh
