### ISSUE TITLE
Works with gen2?

### ISSUE THREAD

**Issue by dcmeglio** [dgreif/homebridge-petsafe-smart-feed#7]
Does this work with the gen2 pet safe feeder (the one with Alexa and dash support?)

**Comment by dgreif** [comment]
Yep, the gen2 is what I have and used to build the plugin.  It's a great pet feeder!

**Comment by dcmeglio** [comment]
Sorry I know this isn't the right forum to ask this, but I've bought two other smart feeders already and got burned. One was $250 and the motor burned out, and the other was $200 and the company went out of business and shut down their cloud servers and now I have a paperweight. Mind if I ask two quick questions?

1.) Does it jam often? or is it pretty reliable at dispensing?
2.) How often does the wifi drop? My Petnet used to show it's "red error" light almost constantly. They blamed Google Wifi saying that they didn't support mesh networks.

Sorry for hijacking your repo, I want to reference your hard work to build a Hubitat integration but I first need to buy the thing and I want to make sure this won't be my THIRD cat feeder to end up in the trash!

**Comment by dgreif** [comment]
@dcmeglio I don't mind you asking at all!  I would definitely recommend the Petsafe Smart Feed, 100%.  I have never had it jam, and the wifi is very reliable.  There are reviews about it needing to be reconfigured if it looses wifi connection, but they must have fixed that issue with a firmware update because I have no problems when I reboot my router and the feeder has to reconnect.  Scheduling feedings is very easy through the app, and also works reliably through HomeKit with this plugin.
